networks:
  mqtt-network:
    driver: bridge
services:
  smart-mqtt:
    container_name: smart-mqtt
    hostname: smart-mqtt
    image: smartboot/smart-mqtt:0.9
    networks:
      mqtt-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  emqx:
    container_name: emqx
    hostname: emqx-mqtt
    image: emqx/emqx:5.0.3
    networks:
      mqtt-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 1883:1883
    user: root:root
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  smart-mqtt-bench:
    depends_on:
      - smart-mqtt
      - emqx
    image: smartboot/smart-mqtt-bench:0.1
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    networks:
      mqtt-network: null
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    command: java -cp smart-mqtt-bench.jar  -Dhost=emqx-mqtt -Dcount=100 org.smartboot.bench.mqtt.Subscribe
version: '3.7'