networks:
  mqtt-network:
    driver: bridge
services:
  mqtt-broker:
    container_name: smart-mqtt
    hostname: mqtt-broker
    image: smartboot/smart-mqtt:latest
    networks:
      mqtt-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    ports:
      - 18083:18083
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

#  mqtt-broker:
#    container_name: emqx
#    hostname: mqtt-broker
#    image: emqx/emqx:5.0.24
#    networks:
#      mqtt-network: null
#    restart: always
#    security_opt:
#      - no-new-privileges:true
#    user: root:root
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "1"

  smart-mqtt-bench:
    depends_on:
      - mqtt-broker
    image: smartboot/smart-mqtt-bench:latest
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    networks:
      mqtt-network: null
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    command: java -cp smart-mqtt-bench.jar  -Dhost=mqtt-broker -Dconnect=1000 -Dqos=2 -Dpublisher=10 -Dcount=1 -Dpayload=128 org.smartboot.bench.mqtt.Subscribe
#    command: java -cp smart-mqtt-bench.jar  -Dhost=mqtt-broker -Dconnect=2000 -Dqos=2 -Dcount=10 -Dpayload=128 org.smartboot.bench.mqtt.Publish
version: '3.7'