# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 发布 smart-mqtt-bench

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        name: 下载 feat
        with:
          repository: smartboot/feat
          path: feat
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Set up Maven 3.9
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.0'
      - name: Build Feat
        run: mvn -B install --file feat/pom.xml -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      - name: Build smart-mqtt-bench
        run: mvn -B clean install -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      - name: Build smart-mqtt-bench
        run: mvn -f smart-mqtt-bench -B clean install -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: smart-mqtt-bench
          push: true
          no-cache: true
          tags: smartboot/smart-mqtt-bench:latest
          platforms: linux/amd64,linux/arm64