# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: smart-mqtt native

on:
  push:
    branches: [ "master" ]
    tags:
      - v**
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    name: smart-mqtt native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #windows-latest
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/checkout@v4
        name: 下载 smart-socket
        with:
          repository: smartboot/smart-socket
          path: smart-socket
      - uses: actions/checkout@v4
        name: 下载 feat
        with:
          repository: smartboot/feat
          path: feat
      - uses: actions/checkout@v4
        name: 下载 smart-mqtt
        with:
          repository: smartboot/smart-mqtt-enterprise
          token: ${{ secrets.GH_PAT }}
          path: smart-mqtt-enterprise
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Maven 3.9
        uses: stCarolas/setup-maven@v5
#        with:
#          maven-version: '3.9.0'
      - name: Build smart-socket
        run: mvn -B install --file smart-socket/smart-socket-parent/pom.xml -DskipTests
      - name: Build Feat
        run: mvn -B install --file feat/pom.xml -DskipTests
      - name: Build smart-mqtt
        run: mvn -B install --file pom.xml -DskipTests
      - name: Build smart-mqtt-enterprise
        run: mvn -B -f smart-mqtt-enterprise/poms/enterprise.xml clean package -DskipTests
      - name: Build smart-mqtt-enterprise
        run: cp smart-mqtt-enterprise/poms/target/smart-mqtt-broker-*.jar  smart-mqtt-enterprise/smart-mqtt.jar

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run HelloWorld.java
        run: |
          native-image -jar smart-mqtt-enterprise/smart-mqtt.jar

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: smart-mqtt-${{ matrix.os }}
          path: smart-mqtt
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          context: smart-mqtt-enterprise
#          push: true
#          platforms: linux/amd64,linux/arm64
#          tags: smartboot/smart-mqtt:latest