# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 发布至 Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/checkout@v4
        name: 下载 smart-mqtt
        with:
          repository: smartboot/smart-mqtt-enterprise
          token: ${{ secrets.GH_PAT }}
          path: smart-mqtt-enterprise
      - name: Set up Maven 3.9
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.0'
      - name: Build smart-mqtt
        run: mvn -B install --file pom.xml -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      - name: Build smart-mqtt-enterprise
        run: mvn -B -f smart-mqtt-enterprise/plugins/pom.xml clean install -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      - name: Build smart-mqtt-enterprise
        run: mvn -B -f smart-mqtt-enterprise/poms/enterprise.xml clean package -DskipTests -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
      - name: Build smart-mqtt-enterprise
        run: cp smart-mqtt-enterprise/poms/target/smart-mqtt-broker-*.jar  smart-mqtt-enterprise/smart-mqtt.jar
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: smart-mqtt-enterprise
          push: true
#          file: Dockerfile
          tags: smartboot/smart-mqtt:latest